### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by salva00** [salva00/ProgettoIS-Cashback#3]
https://github.com/salva00/ProgettoIS-Cashback/blob/c9b54f2fe49eb58d5233ee0884c93dfaefe53432/src/boundary/FormInserimento.java#L52

@annaamodio bisogna dare come parametro di ingresso un oggetto ```FlowLayout```

**Comment by annaamodio** [comment]
@salva00 lo fa, ma la finestra non è più come la avevamo disegnata, tutti i textfield e le label sono in posizioni diverse. Conviene lasciarlo com'era secondo me
